// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiEsTscezhpAuH9dftBseI3XJvWJxulsM',
    appId: '1:254981039201:web:014da18bdbd80176f1b620',
    messagingSenderId: '254981039201',
    projectId: 'mess-v4',
    authDomain: 'mess-v4.firebaseapp.com',
    storageBucket: 'mess-v4.firebasestorage.app',
    measurementId: 'G-EFZFM6SWW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGgTsN7UqZETJs6zFodH1mDIky3ppE6h8',
    appId: '1:254981039201:android:6a51f44e2328f386f1b620',
    messagingSenderId: '254981039201',
    projectId: 'mess-v4',
    storageBucket: 'mess-v4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsufWzFs_DtX27uWuh6L1zlBsTnvY2vO4',
    appId: '1:254981039201:ios:4cba2dcf4605e184f1b620',
    messagingSenderId: '254981039201',
    projectId: 'mess-v4',
    storageBucket: 'mess-v4.firebasestorage.app',
    iosBundleId: 'com.example.messV4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsufWzFs_DtX27uWuh6L1zlBsTnvY2vO4',
    appId: '1:254981039201:ios:4cba2dcf4605e184f1b620',
    messagingSenderId: '254981039201',
    projectId: 'mess-v4',
    storageBucket: 'mess-v4.firebasestorage.app',
    iosBundleId: 'com.example.messV4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiEsTscezhpAuH9dftBseI3XJvWJxulsM',
    appId: '1:254981039201:web:608dc30a33faafa7f1b620',
    messagingSenderId: '254981039201',
    projectId: 'mess-v4',
    authDomain: 'mess-v4.firebaseapp.com',
    storageBucket: 'mess-v4.firebasestorage.app',
    measurementId: 'G-3RL4R046KK',
  );
}
